In [6]:
import cv2
import numpy as np

img1 = cv2.imread(r'C:\Vscode\Jupyter Notebook\W13 L1\Image1.jpg')
img2 = cv2.imread(r'C:\Vscode\Jupyter Notebook\W13 L1\Image2.jpg')

img1 = cv2.cvtColor(img1, cv2.COLOR_BGR2GRAY)
img2 = cv2.cvtColor(img2, cv2.COLOR_BGR2GRAY)


def mse(img1 , img2):
    h, w = img1.shape
    diff = cv2.subtract(img1, img2)
    err = np.sum(diff**2)
    mse = err/(float(h*w))
    return mse,diff

error, diff = mse(img1, img2)
print(error,diff) 

66.59750435670934 [[19 54 61 ...  0  0  0]
 [20 50 44 ...  0  0  0]
 [26 62 63 ...  0  0  0]
 ...
 [20 45 55 ...  0  0  0]
 [24 64 74 ...  0  0  0]
 [36 75 82 ...  0  0  0]]
